### ISSUE TITLE
[Question] Can author introduce the current maintain state of sawfish?

### ISSUE THREAD

**Issue by tumashu** [SawfishWM/sawfish#14]
Sawfish is a good wm for emacs user,  but I get a sad news that sawfish is stop maintain at 2007, In my opinion, short description about maintain history and maintain future should be showed at point. thanks.

**Comment by Nanolx** [comment]
In fact the opposit is the case: the development *restarted* in 2007. As you can see the lastest commits are from March 2015 and the last Release (1.11) from November 2014.
