### ISSUE TITLE
Screen edge maximization broken

### ISSUE THREAD

**Issue by hoplaahei** [SawfishWM/sawfish#17]
Setting edge action to maximize when dragging window in the Sawfish UI does not properly maximize the screen. Instead the window gets locked in position and can only be moved horizontally until it gets unmaximized again.

**Comment by hoplaahei** [comment]
Should clarify this applies to all windows, and not just the Sawfish UI window. I just set the edge action to maximize when moving window from within the UI rather than editing config file directly. Happens in all versions of Sawfish I've tried, even from a vanilla config.

**Comment by Nanolx** [comment]
Did you try this with a clean configuration aswell? I can not reproduce this.

What keyboard layout are you using? Maybe running sawfish with '--5-buttons' params will do the trick.

**Comment by hoplaahei** [comment]
Yes I've tried it on a few fresh installs where I haven't copied over any configs yet (Arch, Slackware, FreeBSD packages, git) and always the same problem. Really confused as to what is causing the problem.

**Comment by hoplaahei** [comment]
Oh I have it working now with the --5-buttons parameter. Thanks.
