### ISSUE TITLE
Edge flipping delay not working as intended?

### ISSUE THREAD

**Issue by elliotkendall** [SawfishWM/sawfish#20]
I recently updated to Ubuntu 16.04, which includes sawfish 1.11. In the new version, edge flipping works very differently from how it did before. In earlier versions, the delay before flipping workstations/viewports was how long you had to keep the mouse cursor at the edge before the flip occurred. Now it seems to be how long before flipping occurs once the mouse cursor has touched the edge at all, no matter how briefly.

To see this behavior with the default settings, enable edge actions and configure all the directions to perform flip-viewport. "Tap" the mouse cursor against the side of the screen in a direction that has another viewport by moving it to the edge and then quickly moving it back to the middle of the screen. When the delay is up, the viewport will flip even though the mouse cursor is no longer at the edge. This behavior is especially glaring with a long delay like 2000 ms.

I don't know if this is intended behavior, but it's certainly different from the old behavior and I find it pretty perplexing.

**Comment by Nanolx** [comment]
I'll have a look at it.

**Comment by Nanolx** [comment]
Fixed, see commit 8a4282848dd8f9258ce6e3818255a16f22b10681
