### ISSUE TITLE
configure does not recognize rep-gtk if libgtk2.0-dev not installed on Linux Mint 18.1

### ISSUE THREAD

**Issue by cynthia-rempel** [SawfishWM/sawfish#25]
Installed rep-gtk, and configure script couldn't locate rep-gtk.
Installed libgtk2.0 and configure script could find rep-gtk.
Please add check for libgtk2.0, or fix check for rep-gtk, so it will error out in more descriptive way.
Thanks for making this amazing build puzzle!

**Comment by Nanolx** [comment]
It does check for libgtk2.0, but **before** rep-gtk. I've reversed the order, should fix your issue. re-open in case it doesn't.
