### ISSUE TITLE
Build system fails if rep (as opposed to just librep-dev) is not installed on Linux Mint 18.1

### ISSUE THREAD

**Issue by cynthia-rempel** [SawfishWM/sawfish#26]
configure did not produce errors, but couldn't build until rep package was installed.  Please add check for rep (in addition to librep-dev).
Thanks for amazing build puzzle!

**Comment by cynthia-rempel** [comment]
Looks like replacing repexecdir with sawfishexecdir in src/Makefile.in might also solve the problem... If not, then this would be a third problem.

**Comment by Nanolx** [comment]
should be fixed now. re-open if not.
