### ISSUE TITLE
DOC file does not build reproducibly

### ISSUE THREAD

**Issue by bmwiedemann** [SawfishWM/sawfish#31]
Apart from #29 (already merged) and #30 there is one remaining issue, where the DOC file is created with indeterminism from filesystem readdir ordering.

It is created in
```
for d in sawfish/wm; do \
  SAWFISHLISPDIR=. SAWFISHEXECDIR=../src/.libexec SAWFISHDOCFILE=../DOC SAWFISH_USER_LISP_DIR= ../src/sawfish --batch --no-rc compiler -f compile-lib-batch $d; \
done
```

and prints messages such as `compiling sawfish/wm/placement.jl` but I cannot find the code where the readdir (or glob *.jl) is done.

**Comment by bmwiedemann** [comment]
Now I found something in the librep package: https://github.com/SawfishWM/librep/blob/master/lisp/rep/vm/compiler.jl#L315

**Comment by bmwiedemann** [comment]
Strangely enough in a quick test with `emacs --script`, `directory-files` seemed to return sorted entries and the docs say there is a 'nosort' option to disable it. Or is your lisp interpreter different?
Also there is a 'match' option, that would make the code easier to read.

**Comment by Nanolx** [comment]
`rep` is indeed different, it's a Lisp dialect written to match the original authors needs, for example also has Scheme like elements and so on.

You may want to give this a try:

`(sort (directory-files "directory") <)`

the predicate `<` is optional and means ascending, while `>` would be descending. If no predicate is given `<` is assumed.

The sorting then ends up to be

```
.
..
.A
.B
.a
.b
AA
BB
bb
cc
```

hidden files > visible files && uppercase > lowercase.
