### ISSUE TITLE
image of window does not disappear after closure

### ISSUE THREAD

**Issue by cheneymx** [SawfishWM/sawfish#36]
![sawfish_prob](https://user-images.githubusercontent.com/34898557/34625904-cd5304b8-f25a-11e7-9738-faea5cf73dc2.png)
Hi, 
in the Ubuntu 17.10, I installed sawfish-deb-packages (sawfish 1.11.90, rep-gtk 0.90.8.2 and rep 0.92.5) from the official source. 
In the sawfish mode, the image of a window remains, after it is moved away or closed (see the attached pic). I tried lots of methods, but none of them worked, not even reinstallation of Ubuntu.
Any idea, how I can solve this problem?   
(p.s. no problem with gnome shell)

Best regards
cheneymx

**Comment by RobertZenz** [comment]
This looks like nothing is drawing a desktop. Do you have an application running that is supposed to draw the desktop?

**Comment by cheneymx** [comment]
Hi Robert, 
your explanation makes sense! But I have to ask again, what kind of application does such job in gnome?  Or which application will do this job?  Sorry, I can not find useful information by using the keyword "desktop-drawing", except IDesk. 
Best regards
cheneymx

**Comment by RobertZenz** [comment]
Gnome? Uh...I'm not even sure if they support other WMs anymore. Maybe asking them would be a better idea.

I *believe* that it should be Nautilus, but that might have changed sometime during Gnome3 to be a responsibility of the WM.

**Comment by cheneymx** [comment]
Thx for the help. I use the "feh" to draw the desktop and the problem is gone.
