### ISSUE TITLE
startkde renamed

### ISSUE THREAD

**Issue by tkorvola** [SawfishWM/sawfish#43]
The KDE start command appears to have been renamed from `startkde` to `startplasma-x11`. This breaks `sawfish-kde5.desktop` and its session script. In Debian the change occurred between plasma-workspace versions 4:5.14.5.1-1 and 4:5.17.5-4. `ln -s startplasma-x11 startkde` seems to fix it, but is perhaps not the ideal long run solution.

**Comment by Nanolx** [comment]
reading up the docs for various distros shows that `startplasma-x11` indeed is the way to go now.

I've changed our startup script in 16f76e110002bd4753a8ff27cf9fa48f623fd9d1
