### ISSUE TITLE
Windows with _NET_WM_STRUT_PARTIAL aren't recognized as struts

### ISSUE THREAD

**Issue by marstj** [SawfishWM/sawfish#6]
In sawfish.wm.state.wm-spec, windows with _NET_WM_STRUT are recognized as struts, but not those with _NET_WM_STRUT_PARTIAL. The latter property is now the recommended one to use - see http://standards.freedesktop.org/wm-spec/1.3/ar01s05.html, and there are desktop environments that no longer set _NET_WM_STRUT, e.g. xfce4-panel 4.8.6.

One effect of this is that workarea-changed-hook isn't called correctly after XFCE has placed its panels.

Extending update-strut in wm-spec.jl to detect _NET_WM_STRUT_PARTIAL as well would be trivial, but more work might be necessary to fully support the newer partial strut geometries.

**Comment by teika-kazura** [comment]
If anyone wants to fix this...

In fact, Sawfish recognizes _NET_WM_STRUT, so the change won't be so difficult. The files to touch are lisp/sawfish/wm/state/wm-spec.jl and lisp/sawfish/wm/util/workarea.jl .

Hope Chris and everyone are doing well.

Best wishes,
Teika

**Comment by teika-kazura** [comment]
This patch minimally supports _NET_WM_STRUT_PARTIAL. See the diff for the details.
[diff.txt](https://github.com/SawfishWM/sawfish/files/11684722/diff.txt)

(The attached file is a patch, but github doesn't allow the extensio .patch nor .diff. )

Regards.

**Comment by Nanolx** [comment]
patch applied, thanks!

**Comment by teika-kazura** [comment]
Thanks a lot Chris. I really appreiciate you've been taking care of Sawfish, meaning taking care of us all! :)
